# This workflow will build and push a VUE application to an Azure Static Site on Azure Storage.
# To configure this workflow:
# 1. Set up a secret in your repository named storage with the Azure storage connection string.
# 2. Define the AZURE_WEBAPP_NAME and NODE_VERSION (below).
on: [push]
#  release:
#    types: [created]

env:
  AZURE_WEBAPP_NAME: AZURE_WEBAPP_NAME    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        # build the VUE APP
        npm run build --if-present
        # npm run test --if-present
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: ./dist
        # The name of the storage account container these assets will be uploaded to
        container_name: '$web' 
        # The connection string for the storage account
        connection_string: ${{ secrets.storage }}
        # extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`
        extra_args: # optional        